spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
      write-date-keys-as-timestamps: false
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guicao?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: root
  #minio配置
  minio:
    access-key:
    secret-key:
    url:   #访问地址
    bucket-name:

server:
  port: 8081

############## Sa-Token (https://sa-token.cc) ##############
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  active-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  allow-concurrent-login: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid


email:
  config:
    host: smtp.qq.com        # QQ邮箱的SMTP服务器地址
    port: 587                # SMTP服务器端口，对于QQ邮箱TLS为587
    sender: "guoyumingabc@qq.com"  # QQ邮箱地址
    password: "jbizohrbqlzncjgc"  # QQ邮箱生成的授权码
    protocol: smtps          # 协议类型，对于QQ邮箱为smtps

sms:
  config:
    AccessKeyID:
    AccessKeySecret: